[package]
name = "attic"
version = "0.1.0"
authors = ["David Janke <david.janke@numberMumbler.com>"]

[dependencies]
arrayref = "0.3"
base64 = "0.9"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
