[package]
name = "attic-core-lib"
version = "0.1.0"
authors = ["David Janke <david.janke@numberMumbler.com>"]

[dependencies]
arrayref = "0.3"
base64 = "0.9"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
